// Mapping of each EN 18031 requirement → technical assessments required.
// "완전성" = functional completeness, "충분성" = functional sufficiency.
// Some requirements (e.g. CCK-2) only require a conceptual-level completeness
// review. Requirements not listed or listed with `[]` have no technical
// assessment obligation.

import type { AssessmentType } from "./types";

export const ASSESSMENTS_MAP: Record<string, AssessmentType[]> = {
  // ── EN 18031-1 ────────────────────────────────────────────────
  "P1.ACM-1": ["completeness", "sufficiency"],
  "P1.ACM-2": ["sufficiency"],
  "P1.AUM-1-1": ["completeness", "sufficiency"],
  "P1.AUM-1-2": ["completeness", "sufficiency"],
  "P1.AUM-2": ["sufficiency"],
  "P1.AUM-3": ["sufficiency"],
  "P1.AUM-4": ["sufficiency"],
  "P1.AUM-5-1": ["sufficiency"],
  "P1.AUM-5-2": ["sufficiency"],
  "P1.AUM-6": ["sufficiency"],
  "P1.SUM-1": ["sufficiency"],
  "P1.SUM-2": ["sufficiency"],
  "P1.SUM-3": ["sufficiency"],
  "P1.SSM-1": ["completeness", "sufficiency"],
  "P1.SSM-2": ["sufficiency"],
  "P1.SSM-3": ["sufficiency"],
  "P1.SCM-1": ["completeness", "sufficiency"],
  "P1.SCM-2": ["sufficiency"],
  "P1.SCM-3": ["sufficiency"],
  "P1.SCM-4": ["sufficiency"],
  "P1.RLM-1": ["completeness", "sufficiency"],
  "P1.NMM-1": ["sufficiency"],
  "P1.TCM-1": ["sufficiency"],
  "P1.CCK-1": ["completeness", "sufficiency"],
  "P1.CCK-2": ["conceptual_completeness"],
  "P1.CCK-3": ["completeness", "sufficiency"],
  "P1.GEC-1": ["completeness", "sufficiency"],
  "P1.GEC-2": ["completeness"],
  "P1.GEC-3": ["completeness", "sufficiency"],
  "P1.GEC-4": ["completeness"],
  "P1.GEC-5": ["completeness"],
  "P1.GEC-6": ["completeness", "sufficiency"],
  "P1.CRY-1": ["completeness", "sufficiency"],

  // ── EN 18031-2 ────────────────────────────────────────────────
  "P2.ACM-1": ["completeness", "sufficiency"],
  "P2.ACM-2": ["sufficiency"],
  "P2.ACM-3": ["sufficiency"],
  "P2.ACM-4": ["sufficiency"],
  "P2.ACM-5": ["sufficiency"],
  "P2.ACM-6": ["sufficiency"],
  "P2.AUM-1-1": ["completeness", "sufficiency"],
  "P2.AUM-1-2": ["completeness", "sufficiency"],
  "P2.AUM-2-1": ["sufficiency"],
  "P2.AUM-2-2": ["sufficiency"],
  "P2.AUM-3": ["sufficiency"],
  "P2.AUM-4": ["sufficiency"],
  "P2.AUM-5-1": ["sufficiency"],
  "P2.AUM-5-2": ["sufficiency"],
  "P2.AUM-6": ["sufficiency"],
  "P2.SUM-1": ["sufficiency"],
  "P2.SUM-2": ["sufficiency"],
  "P2.SUM-3": ["sufficiency"],
  "P2.SSM-1": ["completeness", "sufficiency"],
  "P2.SSM-2": ["sufficiency"],
  "P2.SSM-3": ["sufficiency"],
  "P2.SCM-1": ["completeness", "sufficiency"],
  "P2.SCM-2": ["sufficiency"],
  "P2.SCM-3": ["sufficiency"],
  "P2.SCM-4": ["sufficiency"],
  "P2.LGM-1": ["sufficiency"],
  "P2.LGM-2": ["sufficiency"],
  "P2.LGM-3": ["sufficiency"],
  "P2.LGM-4": ["sufficiency"],
  "P2.DLM-1": ["completeness", "sufficiency"],
  "P2.UNM-1": ["completeness", "sufficiency"],
  "P2.UNM-2": ["completeness", "sufficiency"],
  "P2.CCK-1": ["completeness", "sufficiency"],
  "P2.CCK-2": ["conceptual_completeness"],
  "P2.CCK-3": ["completeness", "sufficiency"],
  "P2.GEC-1": ["completeness", "sufficiency"],
  "P2.GEC-2": ["completeness", "sufficiency"],
  "P2.GEC-3": ["completeness", "sufficiency"],
  "P2.GEC-4": ["completeness", "sufficiency"],
  "P2.GEC-5": ["completeness"],
  "P2.GEC-6": ["completeness"],
  // P2.GEC-7 (external sensing documentation) — not in assessment mapping; no technical assessment required
  "P2.GEC-7": [],
  "P2.CRY-1": ["completeness", "sufficiency"],

  // ── EN 18031-3 ────────────────────────────────────────────────
  "P3.ACM-1": ["completeness", "sufficiency"],
  "P3.ACM-2": ["sufficiency"],
  "P3.AUM-1-1": ["completeness", "sufficiency"],
  "P3.AUM-1-2": ["completeness", "sufficiency"],
  "P3.AUM-1-3": ["completeness", "sufficiency"],
  "P3.AUM-2-1": ["sufficiency"],
  "P3.AUM-2-2": ["sufficiency"],
  "P3.AUM-3": ["sufficiency"],
  "P3.AUM-4": ["sufficiency"],
  "P3.AUM-5-1": ["sufficiency"],
  "P3.AUM-5-2": ["sufficiency"],
  "P3.AUM-6": ["sufficiency"],
  "P3.SUM-1": ["sufficiency"],
  "P3.SUM-2": ["sufficiency"],
  "P3.SUM-3": ["sufficiency"],
  "P3.SSM-1": ["completeness", "sufficiency"],
  "P3.SSM-2": ["sufficiency"],
  "P3.SSM-3": ["sufficiency"],
  "P3.SCM-1": ["completeness", "sufficiency"],
  "P3.SCM-2": ["sufficiency"],
  "P3.SCM-3": ["sufficiency"],
  "P3.SCM-4": ["sufficiency"],
  "P3.LGM-1": ["sufficiency"],
  "P3.LGM-2": ["sufficiency"],
  "P3.LGM-3": ["sufficiency"],
  "P3.LGM-4": ["sufficiency"],
  "P3.CCK-1": ["completeness", "sufficiency"],
  "P3.CCK-2": ["conceptual_completeness"],
  "P3.CCK-3": ["completeness", "sufficiency"],
  "P3.GEC-1": ["completeness", "sufficiency"],
  "P3.GEC-2": ["completeness"],
  "P3.GEC-3": ["completeness", "sufficiency"],
  "P3.GEC-4": ["completeness"],
  "P3.GEC-5": ["completeness"],
  "P3.GEC-6": ["completeness"],
  // P3.GEC-7 does not exist in code (standard explicitly skipped); no mapping needed
  "P3.GEC-8": ["completeness", "sufficiency"],
  "P3.CRY-1": ["completeness", "sufficiency"],
};

export function assessmentsFor(requirementId: string): AssessmentType[] {
  return ASSESSMENTS_MAP[requirementId] ?? [];
}
